spring:
  cloud:
    gateway:
      routes:
        - id: short-link-admin
          uri: lb://short-link-admin/api/short-link/admin/**
          predicates:
            - Path=/api/short-link/admin/**
          filters:
            - name: JwtValidate
              args:
                whitePathList:
                  - /api/short-link/admin/v1/user/login
                  - /api/short-link/admin/v1/user/has-username
                  - /api/short-link/admin/v1/user/register
                  - /api/short-link/admin/v1/user/refresh
        - id: short-link-project
          uri: lb://short-link-project/api/short-link/**
          predicates:
            - Path=/api/short-link/**
          filters:
            - name: JwtValidate
short-link:
  token:
    secret-key: QHYsOmctay12RV44RGBTJXYwWyZiJ3VOcFhFViVOQ31qbGZXK0F6XzYhMiIlVDd3aEUnakI/bDVZaS12d3FwJw==
