server:
  port: 8000
spring:
  application:
    name: short-link-gateway
  profiles:
    active: dev
  data:
    redis:
      host: 192.168.150.102
      port: 6379
      password:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.150.102:8848
